services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports: [9090:9090]
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes: [grafana-data:/var/lib/grafana]
    ports: [3000:3000]
    depends_on: [prometheus]
  chungus:
    build: .
    volumes: [./:/app]
    ports: [3001:3000]

volumes:
  prometheus-data:
  grafana-data:
